### ISSUE TITLE
Correction of the fv_atof in the Lib repo

### ISSUE THREAD

**Issue by MKcodes2** [dendeaisd/MiniRT#26]
We need to update the fv_atof, because for numbers with no sign in front, it skips the first character.

**Comment by MKcodes2** [comment]
I sent you my correction, that seems to work, on slack. I only changed 2 lines in your function.

**Comment by flavify** [comment]
Is this very important? Should I do i now?

**Comment by MKcodes2** [comment]
No, you shouldn't do it now. 
I found a temporary solution.
All good. 😁

**Comment by MKcodes2** [comment]
Now we don't really need this, since I have the ft_atof in the. src/utils/ folder.
